### ISSUE TITLE
NoSuchMethodError in protobuf / ver > 2.17.3

### ISSUE THREAD

**Issue by vogt31337** [FasterXML/jackson-dataformats-binary#688]
Hi,

when using version > 2.17.3 I get the following Exception (I think this was version 2.18.5):

```java
java.lang.NoSuchMethodError: 'void com.fasterxml.jackson.core.base.ParserMinimalBase.<init>(int, com.fasterxml.jackson.core.StreamReadConstraints)'
at com.fasterxml.jackson.dataformat.protobuf.ProtobufParser.<init>(ProtobufParser.java:296)
at com.fasterxml.jackson.dataformat.protobuf.ProtobufFactory._createParser(ProtobufFactory.java:249)
at com.fasterxml.jackson.dataformat.protobuf.ProtobufFactory.createParser(ProtobufFactory.java:173)
at com.fasterxml.jackson.dataformat.protobuf.ProtobufFactory.createParser(ProtobufFactory.java:13)
at com.fasterxml.jackson.databind.ObjectReader.createParser(ObjectReader.java:1149)
at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1603)
```

Seems to happen with all versions > 2.17.3 & < 3.x

I think it tries to call the constructor directly but afaik com.fasterxml.jackson.core.StreamReadConstraints provides only a factory method.

**Comment by cowtowncoder** [comment]
Almost certainly version incompatibility: you have too old `jackson-core`; its minor version MUST be at or above that of `jackson-dataformat-protobuf`. So when upgrading protobuf to 2.17.3, jackson-core needs to be at least 2.17.0 (and so forth).

Usually you should align minor versions of all Jackson components.
A good way to do that is to use `jackson-bom` to get consistent version set (https://github.com/FasterXML/jackson-bom/)

**Comment by vogt31337** [comment]
@cowtowncoder , I did use the same version number for all jackson tools. It is a programming error not covered by the tests. Only solution was to downgrade all versions to the mentioned ones.
If you look into the code, you can see that indeed there is something missing.

**Comment by cowtowncoder** [comment]
> If you look into the code, you can see that indeed there is something missing.

I am not sure what do you mean with "look into the code" here.

But no, error message clearly indicates some discrepancy between runtime versions and versions used for compilation.

If you think there is a bug, we'd need a full reproduction to show there is a problem.

**Comment by cowtowncoder** [comment]
No way to reproduce, closing.
